"""Deterministic URL builders.

These are constructed from trip data, never generated by the model, so they
cannot hallucinate and cannot 404 the way a remembered deep link does.
"""
from __future__ import annotations

from datetime import date, timedelta
from urllib.parse import quote_plus

from state import TripState


def maps_search(query: str) -> str:
    return f"https://www.google.com/maps/search/?api=1&query={quote_plus(query)}"


def maps_directions(origin: str, destination: str, mode: str = "transit") -> str:
    return (
        "https://www.google.com/maps/dir/?api=1"
        f"&origin={quote_plus(origin)}&destination={quote_plus(destination)}"
        f"&travelmode={mode}"
    )


def google_flights(origin: str, destination: str, start: str | None) -> str:
    q = f"flights from {origin} to {destination}"
    if start:
        q += f" on {start}"
    return f"https://www.google.com/travel/flights?q={quote_plus(q)}"


def skyscanner(origin: str, destination: str) -> str:
    return f"https://www.skyscanner.net/transport/flights/?query={quote_plus(f'{origin} to {destination}')}"


def booking_search(destination: str, checkin: str | None, checkout: str | None, adults: int = 2) -> str:
    url = f"https://www.booking.com/searchresults.html?ss={quote_plus(destination)}&group_adults={adults}"
    if checkin and checkout:
        url += f"&checkin={checkin}&checkout={checkout}"
    return url


def hostelworld(destination: str) -> str:
    return f"https://www.hostelworld.com/search?search_keywords={quote_plus(destination)}"


def airbnb(destination: str) -> str:
    return f"https://www.airbnb.com/s/{quote_plus(destination)}/homes"


def rome2rio(origin: str, destination: str) -> str:
    return f"https://www.rome2rio.com/s/{quote_plus(origin)}/{quote_plus(destination)}"


def wikivoyage(destination: str) -> str:
    return f"https://en.wikivoyage.org/wiki/Special:Search?search={quote_plus(destination)}"


def visa_check(origin: str, destination: str) -> str:
    return f"https://duckduckgo.com/?q={quote_plus(f'visa requirements {origin} passport to {destination} official')}"


def _checkout_date(start: str | None, days: int | None) -> str | None:
    if not start or not days:
        return None
    try:
        d = date.fromisoformat(start) + timedelta(days=int(days))
        return d.isoformat()
    except (ValueError, TypeError):
        return None


def _adult_count(travelers: str | None) -> int:
    if not travelers:
        return 2
    digits = "".join(ch if ch.isdigit() else " " for ch in travelers).split()
    return int(digits[0]) if digits else 2


def booking_bundle(trip: TripState) -> list[dict[str, str]]:
    """The 'go book this' link set for a finished plan."""
    dest = trip.destination or ""
    origin = trip.origin or ""
    checkout = _checkout_date(trip.start_date, trip.duration_days)
    adults = _adult_count(trip.travelers)

    bundle = [
        {"label": "Compare flights (Google Flights)", "url": google_flights(origin, dest, trip.start_date)},
        {"label": "Compare flights (Skyscanner)", "url": skyscanner(origin, dest)},
        {"label": "Hotels & stays (Booking.com)", "url": booking_search(dest, trip.start_date, checkout, adults)},
        {"label": "Apartments (Airbnb)", "url": airbnb(dest)},
        {"label": "Getting there / around (Rome2Rio)", "url": rome2rio(origin, dest)},
        {"label": "Destination guide (Wikivoyage)", "url": wikivoyage(dest)},
        {"label": "Check visa requirements", "url": visa_check(origin, dest)},
    ]
    if trip.accommodation and "hostel" in trip.accommodation.lower():
        bundle.insert(4, {"label": "Hostels (Hostelworld)", "url": hostelworld(dest)})
    return bundle


def map_link_for(place: str, city: str | None) -> str:
    return maps_search(f"{place}, {city}" if city else place)
